server:
  port: 8080

spring:
  application:
    name: product-service
  data:
    mongodb:
      uri: mongodb://admin:1234@172.20.0.2:27017/product?retryWrites=true&authSource=admin

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka