server:
  port: 8084

spring:
  application:
    name: user-service
  data:
    mongodb:
      uri: mongodb://admin:1234@172.20.0.2:27017/user?retryWrites=true&authSource=admin

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka